jobs:
  - job: verify
    pool: server
    steps:
    - task: ContrastIntegration@2
      inputs:
        ContrastService: 'TestContrastConnection'
        Application: '30b2ba47-70a0-4718-8f25-ac6641695ce9'
        CriticalLimit: '0'
        HighLimit: '0'
        MediumLimit: '-1'
        LowLimit: '-1'
        NoteLimit: '-1'
